print("Enter the details of student ")
print("----------------------------")
name=input("enter the student name:")
print(name)
print("-----------------------------")
print("ENTER THE FEE DETAILS")
print("-----------------------------")
admission_fee=int(input("Enter the admission fees:"))
print("-----------------------------")
tuition_Fee=int(input("Enter the tuition fees:"))
print("-----------------------------")
bus_fee=int(input("Enter the bus fee:"))
print("-----------------------------")
hostel_fee=int(input("Enter hostel fees:"))
print("-----------------------------")
total=admission_fee+tuition_Fee+bus_fee+hostel_fee               
print("Total fee is",total)
